### ISSUE TITLE
request new branch for fetch new videos from hashtag/channel , auto dubbed & re-uploaded to own YouTube

### ISSUE THREAD

**Issue by herokuhint** [NIKDISSV-Forever/FastDub#1]
Hi NIKDISSV-Forever ,
please make new branch for fetch new videos from youtube hashtag/channel , auto dubbed & re-uploaded to own YouTube.
waiting for your commit/s.
finest regards

**Comment by NIKDISSV-Forever** [comment]
> 

I'll start working on it

**Comment by NIKDISSV-Forever** [comment]
I completed all the functionality, uploading to YouTube, in my opinion, is not worth such an effort, if there are problems with it, write, but for now it will be a beta version, that is, you need to install it with the command: 
pip install --pre PyFastDub
pip install --pre PyFastDub[YTU]
