### ISSUE TITLE
error when try to dub from youtube to persian (farsi)

### ISSUE THREAD

**Issue by elmirarokni** [NIKDISSV-Forever/FastDub#2]
C:\Users\nojhanacc\Desktop\FastDub-main\New folder>python -m FastDub https://youtu.be/DD5UKQggXTc -yt -v "Yuriy" -l fa
Using Netherlands server backend.
usage: FastDub [-h] [-rc {0,1,2}] [-rf CLEANUP_LEVEL] [-l LANGUAGE] [-tc THREADS_COUNT] [-i INPUT] [-vf VIDEO_FORMAT]
               [-sf SUBTITLES_FORMAT] [-En EXCLUDE [EXCLUDE ...]] [-Eu EXCLUDE_UNDERSCORE]
               [-sc | --sidechain | --no-sidechain] [-sc-msl MIN_SILENCE_LEN] [-sc-st SILENCE_THRESH]
               [-sc-gdo GAIN_DURING_OVERLAY]
               [-v {microsoft david desktop - english united states),microsoft zira desktop - english (united states}]
               [-a ALIGN] [-ll {trace,debug,verbose,info,warning,error,fatal,panic,quiet}]
               [-y | --confirm | --no-confirm] [-yt] [-ak API_KEYS [API_KEYS ...]] [-yts]
               [-yts-l YOUTUBE_SEARCH_LIMIT] [-yts-rg YOUTUBE_SEARCH_REGION] [-ytu]
               [-ytu-ps {private,public,unlisted}] [-ytu-t] [-tr] [--rewrite-srt | --no-rewrite-srt]
               [-ts {alibaba,argos,baidu,bing,caiyun,deepl,google,iciba,iflytek,itranslate,papago,reverso,sogou,tencent,translateCom,utibet,yandex,youdao}]
FastDub: error: argument -v/--voice: invalid choice: 'yuriy' (choose from 'microsoft david desktop - english (united states)', 'microsoft zira desktop - english (united states)')

**Comment by NIKDISSV-Forever** [comment]
Yuri is the voice that will be voiced, it is only suitable for the Russian language, to set the voices for your own language, go to windows settings (Win + I) then click on "Time and language" then on speech recognition and press +

**Comment by elmirarokni** [comment]
Hello again [NIKDISSV-Forever](https://github.com/NIKDISSV-Forever),
I want to dockerized this project & run in ubuntu base os , please help me how to convert it to run in ubuntu 22 or 20 .
waiting for your response
finest regards

**Comment by NIKDISSV-Forever** [comment]
I will release a small update on this today, in ubuntu you will need two additional dependencies:
sudo apt install espeak ffmpeg

**Comment by NIKDISSV-Forever** [comment]
problem solved, closed.
