### ISSUE TITLE
please dockerize & make alternative for using speak voice pack alternative for ubuntu

### ISSUE THREAD

**Issue by elmirarokni** [NIKDISSV-Forever/FastDub#4]
Hello again [NIKDISSV-Forever](https://github.com/NIKDISSV-Forever),
I want to dockerized this project & run in ubuntu base os , please help me how to convert it to run in ubuntu 22 or 20 .
also  make sample python file or sample cmds for dub youtube tag to persian dubbed video.
waiting for your response
finest regards

**Comment by NIKDISSV-Forever** [comment]
As for tags, you need to pass a tag (in quotes) to --input and add two arguments, these are -yt and -yts 
python -m FastDub -i "#anytag" -yt -yts -l fa

**Comment by NIKDISSV-Forever** [comment]
in the readme appeared instructions for installing in ubuntu, closed.
