### ISSUE TITLE
error in logging 

### ISSUE THREAD

**Issue by Momaiz** [NIKDISSV-Forever/FastDub#7]
Hello , Thank your for sharing your package . 
i still testing the package but i got this issue

> FastDub
> https://github.com/NIKDISSV-Forever/FastDub
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/momaiz/.local/lib/python3.8/site-packages/fastdub/__main__.py", line 240, in <module>
>     main()
>   File "/home/momaiz/.local/lib/python3.8/site-packages/fastdub/__main__.py", line 170, in main
>     args = parse_args()
>   File "/home/momaiz/.local/lib/python3.8/site-packages/fastdub/__main__.py", line 66, in parse_args
>     choices=logging.getLevelNamesMapping().keys(),
> AttributeError: module 'logging' has no attribute 'getLevelNamesMapping

I'm using ubuntu  and installed 
sudo apt install espeak ffmpeg and other requirements

can you help please ?

**Comment by NIKDISSV-Forever** [comment]
Today I'll fix it (as soon as you have free time).
The fact is that getLevelNamesMapping only appeared in Python 3.11. If you have such an opportunity right now, you can change the version to 3.11 to not wait for a fix.

Thanks for noticing.
